version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container5
    environment:
      POSTGRES_DB: StudentData
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: sky@2024
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

  springboot_app:
    build: .
    container_name: springboot_app5
    depends_on:
      - postgres
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/StudentData
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: sky@2024
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    ports:
      - "8080:8080"

volumes:
  pg_data: